package es.induserco.opilion.negocio.gestionregistroentrada;

import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Vector;

import es.induserco.opilion.data.entidades.Bulto;
import es.induserco.opilion.data.entidades.Ciclo;
import es.induserco.opilion.data.entidades.Mantenimiento;
import es.induserco.opilion.data.entidades.Maquina;
import es.induserco.opilion.data.entidades.MovimientoVehiculo;
import es.induserco.opilion.data.entidades.RegistroCalidad;
import es.induserco.opilion.data.entidades.RegistroEntrada;
import es.induserco.opilion.data.entidades.RegistroOrden;
import es.induserco.opilion.data.entidades.TipoMantenimiento;
import es.induserco.opilion.data.entidades.TipoMaquina;
import es.induserco.opilion.data.entidades.envasado.LineaProducto;

public interface IGestionRegistroEntradaService {

	public String getCodigoOrden() throws Exception;
	public String getFechaRegistro() throws Exception;
	public Boolean addRegistroOrden(RegistroOrden entry) throws Exception;
	public Boolean addROMovimientoVehiculo(MovimientoVehiculo entry) throws Exception;	
	public Boolean addRegistroEntrada(RegistroEntrada entry,List listindic, List listestados) throws Exception;
	public Boolean updateRegistroEntrada(RegistroEntrada entryf,RegistroEntrada entryu,List listindic, List listestados) throws Exception;
	public Boolean deleteRegistroEntrada(RegistroEntrada entryf) throws Exception;
	public Vector getOrdenes() throws Exception;	
	public Vector <RegistroOrden> getOrdenes(RegistroOrden orden, int filtro) throws Exception;	
	public Vector getRegistrosEntradaOrden(String codigoOrden) throws Exception;
	public Vector getProveedores() throws Exception;
	public Vector getTransportistas() throws Exception;
	public Vector getOperarios() throws Exception;
	public Vector getProductos(String filtro) throws Exception;
	public Vector getEstadosFabas() throws Exception;
	public Vector getCategorias(String codigoEntrada) throws Exception;
	public Vector getFormatos() throws Exception;
	public Vector getVehiculos() throws Exception;
	public Vector getIncidencias() throws Exception;	
	public Vector getRegistroEntradas(String codigoEntrada,Date fecha,Long idProducto) throws Exception;
	public RegistroEntrada loadRegistroEntrada(RegistroEntrada regEntrada) throws Exception;
	public boolean addAnalisisCalidadRegistro(RegistroEntrada entry,
			Long varIGL, Long varSPL, Long varDPL, Long varDAL, Long varML,
			double calidad, String baremoCalidad)throws Exception;
	public String getFechaCaducidad() throws Exception;
	public Vector getCosechas()throws Exception;
	public Vector getProductos()throws Exception;
	public Vector getEnvases()throws Exception;
	public Boolean addRegistroSubEntrada(RegistroEntrada regEntradaFind,RegistroEntrada entry, List listindic, List listestados) throws Exception;
	public Boolean addRegistroSubEntrada(RegistroEntrada regEntradaFind,RegistroEntrada entry, List listindic, List listestados, String tipoProceso) throws Exception;	
	public Vector getTipoUbicaciones()throws Exception;
	public Vector getIncidenciasFiltradas(int filtro)throws Exception;
	public Vector getCategoriasFiltradas(int filtro)throws Exception;
	public String addRegistrosSubEntradaProceso(RegistroEntrada regEntradaFind, Map mapaCategorias,String proceso,Double cantidadProceso) throws Exception;
	public Double getSaldoRegistro(String codigoEntrada) throws Exception;
	public Vector getREENProducto(Long idProducto) throws Exception;	
	public Vector getREENProducto(String codigoEan) throws Exception;		
	public Vector getREENDetalle(String codigoEntrada) throws Exception;
	public RegistroEntrada getEtiquetaRE(String codigoEntrada) throws Exception;
	public Boolean addMQ(Maquina maquina) throws Exception;
	public Boolean addMT(Mantenimiento mant) throws Exception;
	public Vector<TipoMantenimiento> getTipoMant() throws Exception;
	public Vector<Maquina> getMaquinas(long idTipo, long idMaquina, String fecha) throws Exception;
	public Vector<Mantenimiento> getRegistrosMT(long idTipoMant,long idMaquina,String fechaConsulta)throws Exception;
	public Boolean getOrdenEntradaTemporal(RegistroEntrada registroEntrada) throws Exception;
	public Boolean addRegistroEntradaTmp(RegistroEntrada registroEntrada, List listindic, List listestados) throws Exception;
	public Boolean addRegistroEntradaTmp(RegistroEntrada registroEntrada) throws Exception;
	public Vector<RegistroEntrada> getRegistrosEntradaTmp(String codigoOrden) throws Exception;
	public RegistroEntrada getOrdenRegistroTmp() throws Exception;
	public Boolean deleteTemporales(String idOperario) throws Exception;
	public Boolean addRegistrosTemporales(String idOperario) throws Exception;
	public RegistroEntrada loadRegistroEntradaTmp(RegistroEntrada regEntrada) throws Exception;
	public Vector loadEstadoFabasTmp(RegistroEntrada regEntrada) throws Exception;
	public Vector loadIncidenciasTmp(RegistroEntrada regEntrada) throws Exception;
	public Vector loadEstadoFabas(RegistroEntrada regEntrada) throws Exception;
	public Vector loadIncidencias(RegistroEntrada regEntrada) throws Exception;
	public Boolean updateRegistroEntradaTmp(RegistroEntrada regEntradaFind,RegistroEntrada regEntradaActualiza, List listindic, List listestados) throws Exception;
	public Boolean deleteRegistroEntradaTmp(RegistroEntrada regEntradaFind,RegistroEntrada regEntradaElimina) throws Exception;
	public Boolean deleteRegistroEntradaTmp(String idOperario) throws Exception;
	public Boolean deleteOrdenEntrada(String codigoEntrada) throws Exception;
	public RegistroEntrada getOrdenRegistroTmp(String codigoOrden) throws Exception;
	public String getFechaRegistroTmp(String codigoOrden) throws Exception;
	public String getFechaCaducidadTmp(String codigoOrden) throws Exception;
	public String getFechaRegistro(String codigoOrden) throws Exception;
	public String getFechaCaducidad(String codigoOrden) throws Exception;
	public RegistroOrden getOrdenEntrada(String codigoOrden) throws Exception;
	public RegistroOrden getOrdenEntradaTmp(String codigoOrden) throws Exception;
	public Vector<RegistroEntrada> getRegistroEntradas(RegistroEntrada entrada, int filtro) throws Exception;
	public RegistroEntrada getRegistroEntrada(String codigoEntrada) throws Exception;
	public Vector<RegistroCalidad> getRegistrosCalidad(String codigoEntrada) throws Exception;
	public Double addAnalisisCalidadRegistro(RegistroCalidad calidad) throws Exception;
	public Vector getBultosRegistroEntrada(RegistroEntrada entrada)throws Exception;
	public Boolean updateBultoRE(Bulto bulto) throws Exception;
	public Boolean addBultoRE(String idEntrada, int numBulto, double peso) throws Exception;
	public Boolean addBultoRE(Bulto bulto) throws Exception;
	public Boolean inicializaBultosRE(Bulto bulto, double total) throws Exception;
	public Vector<TipoMaquina> getTiposMaquinas() throws Exception;
	public Vector<Mantenimiento> getMantenimientos(long idMantenimientoProgramacion,long idTipo, long idMaquina) throws Exception;
	public Vector<Ciclo> getCiclos() throws Exception;
	public boolean addMTProgramado(Mantenimiento entry) throws Exception;
	public void inseRegMT(Mantenimiento entry) throws Exception;
	public void devolucion(RegistroEntrada entry) throws Exception;
	public void checkMT() throws Exception;
	public Vector<RegistroEntrada> getDevoluciones(String fecha) throws Exception;
	public Vector<Mantenimiento> getMantenimientosProgramados(long tipo,long idMaquina, String fechaConsulta) throws Exception;
	public Boolean updateRegistroOrden(RegistroOrden entry) throws Exception;
	public String generarCodigoEntrada() throws Exception;
	public void reaprovecharDevolucion(LineaProducto linea) throws Exception;
	public Vector<RegistroEntrada> getDevolucionesLote(String lote) throws Exception;
}